/*
 * 	Copyright (C) 2008-2009 Fabian Gebert <fabiangebert@mediabird.net>
 *
 *	This file is part of Mediabird Web2.0-Learning.
 *
 *	Mediabird Web2.0-Learning is free software: you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation, either version 3 of the License, or
 *	(at your option) any later version.
 *
 *	Mediabird Web2.0-Learning is distributed in the hope that it will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *	GNU General Public License for more details.
 *
 *	You should have received a copy of the GNU General Public License
 *	along with Mediabird Web2.0-Learning.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/**
 * English resource strings
 */
client.lang = {
	_H1: 'כותרת 1',
	_H2: 'כותרת 2',
	_H3: 'כותרת 3',
	ADD_LEFT: 'הכניסו דף הערות חדש מימין',
	ADD_REFERENCE: 'הוספת קישור',
	ADD_RIGHT: 'הכניסו דף הערות חדש משמאל',
	ADD_TRANSLATION: 'הוסיפו',
	ANNOTATION: 'הערה',
	ANNOTATE: 'העירו',
	ANSWER: 'תשובה',
	CORRECT_TRANSLATION: 'תרגום נכון',
	ANSWER_MODE_BY_RANGE: 'השתמשו בבחירה',
	ANSWER_MODE_EXPLICIT: 'הגדירו במדוייק',
	ANSWER_MODE: 'מצב תשובה',
	ANSWER_RIGHT: 'ידעתי זאת',
	ANSWER_TOO_LONG: 'תשובה ארוכה מידי.',
	ANSWER_UNSURE: 'חזרו שוב במועד מאוחר',
	ANSWER_WRONG: 'טעיתי',
	BOLD: 'מודגש',
	BOX_LEVEL_BRIDGE: ' on box level ',
	CANCEL: 'ביטול',
	CAPTCHA: 'קוד אבטחה',
	CAPTCHA_MISSING: 'קוד אבטחה חסר',
	CARD_EMPTY: '(דף הערות זה הוא ריק)',
	NOTE_SHEET: 'דף הערות',
	CATEGORY: 'מילות מפתח',
	CLICK_TO_ENTER: '(הקישו כאן לכתיבת הערה חדשה)',
	CLICK_TO_ENTER_ADVANCED: '(הקישו כאן לכתיבת הערות מתקדמות)',
	CLICK_TO_ENTER_ILLUSTRATIVE: '(הקישו כאן כדי להבהיר את הערות שכתבתם עד כה)',
	ILLUSTRATION_OF: 'תרשים של ',
	MORE_DETAILS_ON: 'פרטים נוספים על ',
	CLOSE: 'סגירה',
	CONFIRM_CLOSE: 'אם תאשרו, כל השינויים שלא שמרתם יאבדו',
	CONFIRM_REQUEST_SENT: 'הודעת אישור נשלח לכתובת הדואר שלך',
	ACCOUNT_CREATED: 'Account was created, use your credentials to log in.',
	CONNECTION_DOWN: 'החיבור לא הצליח להישמר והוא ניתק. נסו לרענן את הדף',
	CONNECTION_ERROR: 'החיבור ניתק. נסו לרענן את הדף',
	COPY: 'העתקת הבחירה',
	COPY_SECURITY: 'הפקודה העתק אינה זמינה עקב הגבלה שהוגדרה ע"\י הדפדפן שלכם. אנא השתמשו בקיצור CTRL+C במקום',
	COULD_NOT_UPDATE_TOPIC: 'לא היה יכול לעדכן את תיקיית הערות',
	COULDNT_COPY_IMAGE: 'לא היה יכול להעתיק את התמונה לתיקיית היעד',
	CREATE: 'יצירה',
	CUT: 'חיתוך הבחירה',
	CUT_SECURITY: 'הפקודה גזור אינה זמינה עקב הגבלה שהוגדרה ע"\י הדפדפן שלכם. אנא השתמשו בקיצור CTRL+X במקום',
	DEFINITION: 'הגדרה',
	DEFINE_SELECTION: 'הגדירו',
	DEFINITION_QUESTION: 'מהי ההגדרה של:',
	DELETE: 'מחיקה',
	DESCRIBE_ISSUE: '(הקישו כאן כדי לתאר את הנושא)',
	DESCRIPTION: 'תארו את המאפיין החדש',
	MEDIABIRD_DESCRIPTION: '<p>Mediabird is about learning together. Users can take notes on subjects they want to learn and discuss questions in the context they appear.</p><p>Enter your credentials and click "Log in" or register for a new account using "Register new account".</p>',
	BROWSER_BAD_TEXT: '<h3>הדפדפן או גרסתו אינם נתמכים. עדכנו אותו או התקינו את הדפדפן המומלץ <a href="http://www.getfirefox.com" target="_blank">Firefox</a></h3>',
	EDIT_CARD_FROM_MAP: ' עירכו את תוכן הערה זו',
	EDIT_EMPTY_CARD_FROM_MAP: 'צרו תוכן להערה זו',
	SAVE: 'שמירה',
	SAVE_CLOSE: 'שמירה וסיום',
	CANNOT_DELETE_WHILE_OPEN: 'לא יכול למחוק את דף הערות הנוכחי. אנא פתחו אותו מחדש ונסו שוב',
	CANNOT_DELETE_LAST: 'לא יכול למחוק את דף הערות שנפתח אחרון. הקישו על "ניהול תיקיית הערות" ומחקו את תיקיית הערות הרצויה',
	TRAINER_HEADING: 'זכירת תיקיית הערות',
	EDIT: 'עריכה',
	EDIT_MAP: '<h1>סידור חדש של דף הערות בעזרת העכבר</h1><p>גררו אותם <strong>למטה ולמעלה</strong> כדי לשנות את הרמה שלהם</p>',
	EXTEND_MAP: '<h1>יצירת דפי הערות חדשים או ניווט לדפים קיימים </h1><p>גררו פריט חדש <strong>למעלה ולמטה</strong> כדי לשנות את הרמה שלו</p>',
	EDIT_MAP_ADD: '<h1>הגעתם לדף ההערות האחרון</h1><p>אתם יכולים <strong>להוסיף עוד</strong> ע\"י שימוש במקש -  \'+\'.</p>',
	EDIT_MAP_ADD_LEFT: '<h1>הינכם בדף ההערות הראשון</h1><p>אתם יכולים <strong>להוסיף עוד</strong> ע\"י שימוש במקש -  \'+\'</p>',
	SHOW_MAP: '<h1>ראייה כללית של תיקיית ההערות</h1>',
	EDITOR_TITLE: 'עורך',
	EMAIL: 'דואר ',
	EMAIL_MISSING: 'דואר חסר',
	INVALID_EMAIL: 'רישום דואר לא תקין',
	EMPTY_ROW: '(אין פריטים ברשימה)',
	ENTER_ANNOTATION: '(הקישו כאן לרישום דברי הסבר)',
	ENTER_ANSWER: '(הקישו כאן לרישום תשובה)',
	ENTER_DEFINITION: '(הקישו כאן לרישום ההגדרה של הביטוי הנבחר)',
	SUGGEST_ANSWER: '(הקישו כאן אם ברצונכם להציע תשובה )',
	ENTER_EXPRESSION: '(Click here and enter the expression defined by the selection)',
	ENTER_NEW_CARD_TITLE: 'רישמו כותרת חדשה לדף ההערות',
	ENTER_QUESTION: '(הקישו כאן לרישום שאלה)',
	ERROR_CHANGING_STATUS: 'לא יכול לעדכן את זכויות הגישה לקבוצה זו. נסו לעדכן שוב.',
	ERROR_CREATING_USER: 'הייתה שגיאה ביצירת המשתמש החדש',
	ERROR_FUNCTION_DISABLED: 'הפונקציה נוטרלה ע\"י המנהלן.',
	ERROR_LOADING_TRAINING: 'טעינה אחרונה לא מוצלחת',
	ERROR_MOVE: 'שגיאה במהלך טעינת קובץ',
	ERROR_TYPE: ' סוג קובץ שגוי. יש לטעון תמונות בלבד',
	ERROR_NO_FILE: 'אף קובץ לא נטען',
	ERROR_QUOTA: 'הגעתם למכסת חשבונכם',
	ERROR_SENDING_CONFIRM: 'היתה שגיאה בשליחת הודעת האישור',
	ERROR_TOO_BIG: 'התמונה שבחרתם גדולה מידי.',
	ERROR_WHILE_UPLOADING: 'התמונה לא היתה יכולה להיטען',
	FILE: 'קובץ',
	FLASH_CARD_BOXES: 'קופסאות כרטיסיות',
	FIND_HOW_TO: 'השתמשו ב-  CTRL+F לחיפוש דף ההערות הנוכחי',
	FIND: 'חפש...',
	FLOAT_LEFT: 'עטיפת טקסט מימין',
	FLOAT_NONE: 'no float',
	FLOAT_RIGHT: 'עטיפת טקסט משמאל',
	FLOAT_STYLE: 'Float style',
	FORMAT: 'תבנית',
	FORMULA_CONTAINS_BLACKLISTED: ' קוד LaTeX מכיל תגים אשר הוכנסו לרשימה שחורה',
	FORMULA_TOO_BIG: 'משוואה גדולה מדי בכדי להיות מוצגת',
	FORMULA_TOO_LONG: 'משוואה ארוכה מדי',
	GENERAL_PREFIX: 'חישבו על התשובה עבור כרטיסית הלימוד הבאה מדף ההערות ',
	GET_NEW_CAPTCHA: 'קבלו קוד חדש',
	GET_PASSWORD: 'שכחתם סיסמה',
	GHOST_ENTRY: '(הקישו כאן להוספת פריט חדש)',
	GHOST_TOPIC: '(הקישו כאן להוספת קובץ הערות חדש)',
	GO: 'בצע',
	GOTO_ANSWER: 'הראה תשובה',
	GOTO_QUESTION: 'הראה שוב את השאלה',
	SHOW_CONTEXT: 'הראה הקשר',
	CONTEXT: 'הקשר',
	GROUP: 'קבוצה',
	HEIGHT: 'גובה',
	HIGHLIGHT: 'הדגשה',
	HTML_CODE: 'HTML קוד',
	CODE: 'קוד',
	IMP_LEVEL: 'סומן כחשוב',
	IMP_LEVEL_BY: 'סומן כחשוב ע"\י',
	MARK_IMPORTANT: 'סמן חשוב',
	IN: 'ב - ',
	INDENT: 'הגדלת עומק',
	INSERT_HTML: 'HTML',
	INSERT_CODE: 'קוד דוגמא',
	INSERT_IMAGE: 'תמונה',
	INSERT: 'הכנסה',
	INSERT_LATEX: 'משוואה',
	AUTO_CONVERT_LATEX: 'אוטומטי',
	AUTO_CONVERT_EXPLANATION: 'אוטומטית מחליף את קוד ה- LaTeX מדף ההערות הנוכחי למשוואות',
	AUTO_LATEX_NO_JOBS: 'אף קוד LaTeX לא נמצא על דף ההערות',
	LATEX_SOURCE: 'משוואה',
	INSERT_LINK: 'קישור',
	INSERTORDEREDLIST: 'ספירה',
	INSERTUNORDEREDLIST: 'לחצני בחירה',
	INVALID_END: '" לא תקין',
	INVALID_START: 'הערך של "',
	IS_IN: 'כתוב ב ',
	ISSUE: 'בעיה',
	ASK_QUESTION: 'שאילת שאלה',
	ANSWER_LINK: 'הכנסת שאלה',
	ITALIC: 'כתב נטוי',
	INVITE: 'הזמנה',
	NO_INVITEES_SELECTED: 'לא ציינתם את מי ברצונכם להזמין לקבוצה',
	INVITE_USER: 'הזמנת חבר',
	INVITE_USERS_TO_GROUP: 'הזמנת חבר לקבוצה',
	FOLLOWING_NOT_FOUND: 'החברים הבאים לא יכלו לקבל הזמנה מכיוון שהם אינם רשומים ב- Mediabird: ',
	NONE_INVITED: 'חבריך כבר הוזמנו',
	COULD_NOT_INVITE_USERS: 'לא יכול היה להזמין חברים',
	EMAIL_OR_NAME: 'כתובת דואר',
	NO_USERS_TO_INVITE: '(אין חברים שידוע כי הם יכולים להיות מוזמנים)',
	FURTHER_USERS_INVITE: 'ע"\י כתובת דואר',
	EMAIL_SEPARATE_EXPLANATION: 'כתובות דואר נפרדות עם פסיקים.',
	KNOWN_USERS: 'חברים',
	JUST_ENABLED: 'חשבונכם הופעל בהצלחה. השתמשו בטופס שלמטה כדי להיכנס',
	JUSTIFY_CENTER: 'עימוד למרכז',
	JUSTIFY_FULL: 'עימוד פריסה',
	JUSTIFY_LEFT: 'עימוד לשמאל',
	JUSTIFY_RIGHT: 'עימוד לימין',
	LANGUAGES: ['English', 'Afar', 'Abkhazian', 'Afrikaans', 'Akan', 'Albanian', 'Amharic', 'Arabic', 'Aragonese', 'Armenian', 'Assamese', 'Avaric', 'Avestan', 'Aymara', 'Azerbaijani', 'Bambara', 'Bashkir', 'Basque', 'Belarusian', 'Bengali', 'Bihari', 'Bislama', 'Bosnian', 'Breton', 'Bulgarian', 'Burmese', 'Catalan', 'Chamorro', 'Chechen', 'Chichewa', 'Chinese', 'Church Slavic', 'Chuvash', 'Cornish', 'Corsican', 'Cree', 'Croatian', 'Czech', 'Danish', 'Divehi', 'Dutch', 'Dzongkha', 'Esperanto', 'Estonian', 'Ewe', 'Faroese', 'Fijian', 'Finnish', 'French', 'Fulah', 'Galician', 'Ganda', 'Georgian', 'German', 'Greek', 'Guarani', 'Gujarati', 'Haitian', 'Hausa', 'Hebrew', 'Herero', 'Hindi', 'Hiri Motu', 'Hungarian', 'Icelandic', 'Ido', 'Igbo', 'Indonesian', 'Interlingue', 'Inuktitut', 'Inupiaq', 'Irish', 'Italian', 'Japanese', 'Javanese', 'Kalaallisut', 'Kannada', 'Kanuri', 'Kashmiri', 'Kazakh', 'Khmer', 'Kikuyu', 'Kinyarwanda', 'Kirghiz', 'Kirundi', 'Komi', 'Kongo', 'Korean', 'Kurdish', 'Kwanyama', 'Lao', 'Latin', 'Latvian', 'Limburgish', 'Lingala', 'Lithuanian', 'Luba-Katanga', 'Luxembourgish', 'Macedonian', 'Malagasy', 'Malay', 'Malayalam', 'Maltese', 'Manx', 'Maori', 'Marathi', 'Marshallese', 'Moldavian', 'Mongolian', 'Nauru', 'Navajo', 'Ndonga', 'Nepali', 'North Ndebele', 'Northern Sami', 'Norwegian', 'Norwegian Bokmal', 'Norwegian Nynorsk', 'Occitan', 'Ojibwa', 'Oriya', 'Oromo', 'Ossetian', 'Pāli', 'Panjabi', 'Pashto', 'Persian', 'Polish', 'Portuguese', 'Quechua', 'Raeto-Romance', 'Romanian', 'Russian', 'Samoan', 'Sango', 'Sanskrit', 'Sardinian', 'Scottish Gaelic', 'Serbian', 'Serbo-Croatian', 'Shona', 'Sichuan Yi', 'Sindhi', 'Sinhala', 'Slovak', 'Slovenian', 'Somali', 'Sotho', 'South Ndebele', 'Spanish', 'Sundanese', 'Swahili', 'Swati', 'Swedish', 'Tagalog', 'Tahitian', 'Tajik', 'Tamil', 'Tatar', 'Telugu', 'Thai', 'Tibetan', 'Tigrinya', 'Tonga', 'Tsonga', 'Tswana', 'Turkish', 'Turkmen', 'Twi', 'Uighur', 'Ukrainian', 'Urdu', 'Uzbek', 'Venda', 'Vietnamese', 'Volapuk', 'Walloon', 'Welsh', 'Western Frisian', 'Wolof', 'Xhosa', 'Yiddish', 'Yoruba', 'Zhuang', 'Zulu','Latin','Old Greek','Fusha'],
	LEVEL: 'רמה',
	LEVEL_IMPORTANT: 'חשוב',
	LEVEL_ADVANCED: 'מתקדם',
	LEVEL_ILLUSTRATIVE: 'תאורי',
	LINK_HEADING: 'עורך קישורים',
	LINK_TYPE: 'סוג קישור',
	LINK_REQUIRES_SELECTION: 'Inserting a link requires a selection which is to be linked',
	COLLAPSIBLE_REQUIRES_SELECTION: 'Inserting a collapsible note requires a selection which is to be collapsible',
	LOCATION: 'מיקום',
	LOGON: 'מחובר',
	COULD_NOT_CLOSE_SESSION: 'לא יכול היה לסגור את הפגישה. טען את הדף מחדש כדי להתחיל פגישה חדשה',
	SET_ACCESS_NONE: 'אין הרשאת גישה',
	SET_ACCESS_READ: 'הרשאת קריאה בלבד',
	SET_ACCESS_WRITE: 'הרשאת כתיבה',
	SET_ACCESS_STRUCTURE: 'הרשאה מלאה',
	TOO_MANY_STEPS: 'בתיקיית הערות זו הגעת למספר המקסימלי של דפי הערות',
	MOVE_LEFT: 'הזזה לשמאל',
	MOVE_RIGHT: 'הזזה לימין',
	NAME: 'שם',
	NAME_MISSING: 'שם החבר חסר',
	NO_ANSWER: 'לא רשמת תשובה',
	
	NO_ANNOTATION: 'לא רשמת הערת הסבר',
	NO_DEFINITION: 'לא רשמת הגדרה',
	
	NO_QUESTION: 'לא רשמת שאלה',
	NO_EXPRESSION: 'לא רשמת ביטוי',
	
	NO_CARD_TITLE: '(אף אחד לא נבחר)',
	NO_FLASH_CARDS: 'הדף הנוכחי אינו מכיל אף כרטיסיית לימוד',
	NO_HIGHLIGHT_IN_EMPTY_CARD: 'הפונקציה המודגשת אינה זמינה עבור דפי הערות ריקים',
	NO_URL_GIVEN: 'להכנסת תמונה מ URL עליך להגדיר יעד',
	NO_MARKER_FOR_DEL: 'בחרו תג שעליכם למחוק קודם',
	NOCAT: '(אין מילות מםתח)',
	NOT_CONFIRMED: 'אנא אשרו את כתובת הדואר שלכם ע"\י שימוש בקישור שנשלח אליכם בדואר האישור',
	OK: 'אוקיי',
	OTHER_ERROR: 'שגיאה בזמן גישה לתסריט',
	OUTDENT: 'הפחתת עומק',
	PADDING_BOTTOM: 'חלק תחתון',
	PADDING_LEFT: 'שמאל',
	PADDING_RIGHT: 'ימין',
	PADDING_STYLE: 'סגנון ריפוד',
	PADDING_TOP: 'חלק עליון',
	PARA: 'פסקה',
	PASS_MISSING: 'חסרה סיסמה',
	PASS_NOT_MATCHING: 'סיסמה לא מתאימה',
	PASSWORD_ACCESS_KEY: 'P',
	PASSWORD_ERROR: 'ארעה שגיאה בזמן איחזור הסיסמה שלך',
	PASSWORD_INVALID: 'ארעה שגיעה בשליחת הסיסמה שלך לכתובת הדואר המבוקשת',
	PASSWORD: 'סיסמה',
	PASSWORD_AGAIN: 'חזרה על הסיסמה',
	PASSWORD_NO_USER: '.כתובת הדואר שהכנסת לא מתאימה לחשבון קיים',
	PASSWORD_SENT: 'דואר עם הסיסמה שלך נשלח לכתובת דואר המקושרת לחשבון',
	PASTE: 'הדבק לתוך הבחירה',
	PASTE_SECURITY: 'הפקודה הדבק אינה זמינה עקב הגבלה שהוגדרה ע"\י הדפדפן שלך. אנא השתמשו בקיצור CTRL+V במקום',
	PLEASE_TRANSLATE: 'תרגם ל ',
	QUESTION_EDIT: 'הקישו כדי לערוך ',
	QUESTION: 'שאלה',
	QUESTION_MODE: 'סוג תג',
	QUESTION_TOO_LONG: 'שאלה ארוכה מדי.',
	QUESTION_VIEW: 'הקישו כדי לראות ',
	REFERENCE: 'קישור',
	REDO: 'מחדש',
	REMOVE_FORMAT: 'ביטול עיצוב',
	REMOVE_LINK: 'הסרת קישור',
	REMOVE: 'הסרה',
	REMOVE_THIS: 'מחיקת תווית',
	REMOVE_TRANSLATION: 'הסרה',
	RENAME: 'שינוי שם',
	RENDERING_FAILED: 'רינדור המשוואה לא הצליח',
	REP_LEVEL: 'סומן לחזרה',
	REP_MARKER: 'חזור בהמשך',
	SHARE: 'שיתוף',
	REPEAT: 'חזרה',
	REPEAT_TITLE: 'סימנת את החלק המודגש לחזרה',
	REVIEW_RIGHT: 'ידעתי זאת',
	REVIEW_UNSURE: 'אחליט מאוחר יותר',
	REVIEW_WRONG: 'חזרה נשנת',
	SEARCH: 'חיפוש',
	SEL_REQUIRED_HIGHLIGHT: 'לפני הדגשת קטע עלכם לסמן את הקטע הרצוי',
	SELECT_CARD_EXPLANATION: 'הקישו על דף הערות והאז הקישו על "בחירת דף הערות"',
	SELECT_CARD: 'בחירת דף הערות ',
	SELECTED_TEXT: 'בחירה',
	SET: 'קבעו',
	SESSION_CREATION_ERROR: 'היתה שגיאה ביצירת הפגישה',
	SESSION_FINISHED: 'האימון הסתיים! לא נשארו כרטיסיות לימוד בפגישה זו',
	SESSION_ABORTED: 'טעינת הדף בוטלה',
	SESSION_INVALID: 'נשלח מענה שגוי. זה כנראה נגרם מבאג או מסיום זמן הפגישה. נסו לטעון את הדף מחדש.',
	SIGN_UP: 'רישום חשבון חדש',
	STRIKE_THROUGH: 'קו מחיקת מילים',
	STUDY_CARD_FROM_MAP: 'הצגת דף הערות זו',
	STUDY_TOOL_TITLE: 'צופה',
	TERMS_ACCEPT: 'קראתי והבנתי את <a href="terms.php" target="_blank">תנאי השימוש</a>.',
	TERMS: 'תנאי שימוש',
	TERMS_MISSING: 'עליכם להסכים לתנאי השימוש',
	TITLE: 'כותרת',
	MEDIABIRD_TITLE: 'Mediabird Web2.0-Learning',
	TOPIC_BRIDGE: ', תיקיית פתקים ',
	TOPIC: 'תיקיית פתקים',
	TOPIC_EMPTY: 'תיקיית ההערות ריקה מדפי הערות ולכן לא יכולה להיפתח.',
	TOPICS: 'רשימת תיקיות הפתקים',
	TRANSLATE_INTO: 'תרגם ל',
	TRANSLATION_EDITOR: 'עורך תרגום',
	TRANSLATION_INTO: 'ב',
	TRANSLATION: 'תרגום',
	TRANSLATE: 'תרגם',
	TRANSLATION_MARKER: 'ערוך תרגום',
	TRANSLATION_VIEWER: 'הצג תרגום',
	TYPE_CARD: 'דף פתקים',
	TYPE_EMAIL: 'דואר',
	TYPE_URL: 'כתובת אתר',
	UNDERLINE: 'קו תחתון',
	UNDO: 'שחזור פעולה',
	UNTITLED: 'חדש',
	UPDATE: 'עדכון',
	UPLOAD_BUTTON: 'העלאה',
	PICTURE: 'תמונה',
	URL_INVALID: 'ה URL שציינת לא תקף',
	USER_EMAIL_TAKEN: 'כתובת הדואר שהכנסת כבר בשימוש ע"\י משתמש אחר',
	USER_NAME_TAKEN: 'שם המשתמש שבחרת כבר בשימוש ע"\י חשבון אחר.',
	WIDTH: 'רוחב',
	WRONG_PASSWORD: 'השילוב של שם המשתמש והסיסמה הינו פסול',
	WRONG_SECURITY: 'קוד בטיחות נרשם לא נכון',
	INSERT_COLLAPSIBLE_NOTE_TEXT: '(רשום מלל)',
	INSERT_COLLAPSIBLE: 'מתקפל',
	ADD_PREREQUISITE: 'הוספת דרישת קדם',
	REMOVE_PREREQUISITE: 'הסרת דרישת קדם',
	PREREQUISITES: 'דרישות קדם',
	NO_TITLE_GIVEN: 'לא רשמת כותרת לדרישת הקדם',
	NO_TOPIC_SELECTED: 'לא בחרת תיקיית הערות כדרישת קדם',
	PREREQUISITE: 'דרישת קדם לתיקיית הערות זו',
	EDIT_FIRST_CARD_OF_PREREQUISITE: 'עריכת דף הערות ראשון של דרישות קדם',
	STUDY_PREREQUISITE: 'לימוד דרישת קדם',
	IMAGE_ADJUST_HEADING: 'התאמת מאפייני תמונה',
	IMAGE_UPLOAD_HEADING: 'העלאת תמונה חדשה',
	IMAGE_LOCATION_HEADING: 'שימוש ביעד נתון',
	COULD_NOT_LOAD_TOPICS: 'לא יכול היה לאחזר את הרשימה של תיקיית ההערות',
	COULD_NOT_LOAD_GROUPS: 'לא יכול היה לאחזר את הרשימה של הקבוצה',
	CREATE_GROUP: 'יצירת קבוצה',
	VIEW_MY_GROUPS: 'הצגת הקבוצות שלי',
	REQUEST_LIST_HEADER: 'הזמנות קבוצה ובקשות חברות',
	JOIN_GROUP: 'הצטרפות לקבוצה',
	REQUEST_GROUP: 'בקשת חברות',
	LEAVE_GROUP: 'עזיבת קבוצה',
	ACCEPT_MEMBER: 'אישור',
	REJECT_MEMBER: 'דחייה',
	PENDING: 'מחכה להתייחסות',
	INVITED: 'הוזמן',
	REQUESTED: 'התבקש',
	MEMBER_LIST_HEADERS: ['שם', 'רמה'],
	REQUESTS_LIST_HEADERS: ['קבוצה', 'מידע', 'פעולות'],
	SET_TO: 'קיבוע ל',
	ADMIN_LEVEL: 'מנהל',
	MEMBER_LEVEL: 'חבר',
	EDIT_GROUP_HEADER: 'עריכת קבוצה',
	VIEW_GROUP_HEADER: 'תצוגת קבוצה',
	GROUP_DESCRIPTION: 'תאור',
	GROUP_NAME: 'שם',
	GROUP_CATEGORY: 'מילות מפתח',
	GROUP_ACCESS: 'גישה למי שאינו חבר',
	GROUP_NO_ACCESS: 'הסתרה',
	GROUP_VIEW_ACCESS: 'הראה, אפשר בקשה',
	GROUP_JOIN_ACCESS: 'הראה, אפשר הצטרפות',
	COULD_NOT_UPDATE_GROUP: 'לא היה יכול לעדכן את הקבוצה',
	MEMBER_LIST: 'חברים',
	COULD_NOT_SET_MEMBER_ACCESS: 'לא היה יכול לשנות את רמת הגישה של חבר הקבוצה',
	COULD_NOT_LEAVE_GROUP: 'לא היה יכול לעזוב קבוצה',
	COULD_NOT_JOIN_GROUP: 'לא היה יכול להצטרף לקבוצה',
	COULD_NOT_DELETE_GROUP: 'לא היה יכול למחוק קבוצה',
	CANNOT_REMOVE_NONEMPTY_GROUP: 'לא יכול למחוק קבוצה שיש בה חברים. הסירו קודם את החברים.',
	ACCEPT_INVITATION: 'אישור',
	REJECT_INVITATION: 'התעלם',
	CANCEL_REQUEST: 'הסרת בקשה',
	COULD_NOT_REMOVE_REQUEST: 'לא היה יכול להסיר בקשה',
	COULD_NOT_ACCEPT_REQUEST: 'לא יכול היה לקבל בקשת חברות',
	COULD_NOT_REJECT_REQUEST: 'לא היה יכול לדחות בקשת חברות',
	COULD_NOT_REMOVE_MEMBER: 'לא היה יכול להסיר חברות',
	CANNOT_LEAVE_GROUP_FROM_EDITOR: 'השתמשו במנהל הקבוצות כדי לעזוב קבוצות שאליהם הצטרפתם.',
	REMOVE_MEMBER: 'הסרה מקבוצה',
	TOPIC_LIST_RECENT_HEADING: 'היסטוריה',
	GROUPLIST_HEADINGS: ['קבוצה', 'גישה'],
	GROUPLIST_HEADER: 'שיתופים',
	CLICK_TO_CHANGE_ACCESS: 'הקישו כדי לשנות את רמת הגישה של החברים',
	ADD_GROUP: 'שיתוף תיקיית הערות',
	SHARE_FOLDER: 'ניהול שיתוף',
	SHARE_FOLDER_EXPLANATION: 'ניהול שיתופים של תיקיית ההערות הנוכחית.',
	SHARE_TOPIC_WITH_GROUP: 'שיתוף חדש לתיקיית ההערות הנוכחית',
	FILE_AS: "פרסם כ",
	MEMBER_RIGHTS: 'זכויות חבר',
	RIGHT_READONLY_PRESET: 'הראה',
	RIGHT_WRITE_PRESET: 'הראה וערוך',
	RIGHT_STUCTURE_PRESET: 'הראה, ערוך וסדר מחדש',
	NOT_MEMBER_OF_ANY_GROUP: 'אי-אפשר לחלוק תיקיית הערות אם אינכם חברים בקבוצה. הקישו על "יצירת קבוצה" כדי ליצור אחת',
	COULD_NOT_UPDATE_RIGHT: 'לא יכול היה לעדכן ישירות את השרת',
	PREREQUISITE_ENTER_TITLE: 'הכניסו את הכותרת של דרישת הקדם',
	PREREQUISITE_CHOOSE_TOPIC: 'או בחרו תיקיית הערות של תיקיית הערות נדרשת',
	NONE: 'אין גישה',
	ALREADY_SHARED_WITH_ALL_GROUPS: 'כבר שיתפתם את תיקיית הערות זו עם כל הקבוצות בהם אתם חברים',
	LICENSE_NO_RESERVED: 'תחום ציבורי, אין זכויות שמורות',
	LICENSE_BY: 'Attribution (by)',
	LICENSE_BY_SA: 'Attribution Share Alike (by-sa)',
	LICENSE_BY_ND: 'Attribution No Derivatives (by-nd)',
	LICENSE_BY_NC: 'Attribution Non-commercial (by-nc)',
	LICENSE_BY_NC_SA: 'Attribution Non-commercial Share Alike (by-nc-sa)',
	LICENSE_BY_NC_ND: 'Attribution Non-commercial No Derivatives (by-nc-nd)',
	COULD_NOT_CHANGE_TOPIC_LICENSE: 'לא יכול היה לשנות את הרישון של תיקיית ההערות',
	LICENSE_TEXT: 'רשיון',
	LICENSE_EXPLANATION: 'הסבר מפורט...',
	LICENSE_EXPLANATION_LINK: 'http://creativecommons.org/about/license/',
	LICENSE_HEADER: 'תוכן הרשיון',
	LICENSE_APPLICATION: 'הרישיון מייושם ברגע שתוכן זה משותף עם חברי קבוצה',
	NO_RECENT_ACTIONS: '(היסטוריה ריקה)',
	NO_CARD_SELECTED: ' לא בחרתם דף הערות. הקישו על "בחירת דף הערות" קודם',
	BALLOON_TEXTS: {
	
		DESKTOP: {
			CLIPBOARD_EXPLANATION: '<h3>לוח כתיבה לתגים</h3><p>לכאן הועברו התגים ששינו את מיקומם. חלק מהנייר שבקופסא מצביע על כך שיש תגים ששינו את מיקומם</p>',
			HIGHLIGHTER_EXPLANATION: '<p>כעת, <strong>הדגישו מעט מלל</strong> על דף ההערות</p>',
			NO_TAGS_EXPLANATION: '<h3>קופסאת כרטיסיות</h3><p>עד כה <strong> אין כרטיסיות לימוד</strong> בקופסאת הכרטיסיות</p><p>השתמשו במדגיש <strong>כדי להדגיש הערות</strong> ולהכניס שאלות.</p>',
			NO_TAGS_HERE_EXPLANATION: '<h3>זכירת תיקיית הערות</h3><p>בדף הערות זה <strong>אין כרטיסיות לימוד</strong>.</p><p>השתמשו במדגיש כדי <strong>להדגיש הערות</strong> ולהכניס שאלות</p><p><a title="Memorizes rest of note folder without current note sheet" class="mem" href="javascript:void(0)">זכירת כל תיקיית ההערות</a>.</p>'
		},
		
		EDITOR: {
			TOO_MUCH_CONTENT: '<h3>תוכן חורג מגודל דף הערות</h3><p>להפיכת דף הערות זה לקל יותר להשגה, <strong>השתדלו לקצר</strong>.</p><p class="add-hint">הכניסו <strong>דפי הערות נוספים</strong> לתוכן הנוסף ע"\י שימוש במקש היפוך דף.</p>'
		},
		
		TRAINER: {
			ANSWER_UP: '<h3>כרטיסיית הלימוד הועברה למעלה</h3><p>מכיוון שעניתם על השאלה  <strong>נכונה,</strong>הכרטיסייה עלתה <strong>שלב אחד למעלה</strong>.</p>',
			ANSWER_REVERT: '<h3>כרטיסיית הלימוד הוחזרה אחורה</h3><p>מכיוון שסימנתם את שתשובתכם <strong>כלא נכונה</strong>, הכרטיסייה הועברה <strong>חזרה לשלב הראשון</strong>.</p>',
			ANSWER_DOWN: '<h3>כרטיסיית הלימוד הועברה למטה</h3><p>מכיוון <strong>שלא ידעתם את התשובה</strong> לשאלה, הכרטיסייה ירדה <strong>שלב אחד למטה</strong>.</p>',
			ANSWER_REMOVED: '<h3>הסרת כרטיסיית לימוד</h3><p>מכיוון שעניתם נכונה <strong>ארבע פעמים ברציפות</strong>, הכרטיסיה הוסרה <strong>מפגישת אימון זו</strong>.</p>'
		}
	},
	IMAGE_EDITOR: "עורך תמונות",
	REVERT_CHANGES: "החזרת כל השינויים שנעשו לדף הערות זה",
	REVERT_CHANGES_TEXT: "כל השינויים לדף הערות זה והתגים שלו יאבדו. האם ברצונכם להמשיך?",
	EMPTY_TRASH: "ריקון לוח הכתיבה לתגים",
	MOVE_TO_TRASH: "העברה ללוח הכתיבה לתגים",
	INSERT_FROM_TRASH: "הכנסה מלוח הכתיבה לתגים",
	
	CARD_UPDATE_PENDING: "הערותיך נשמרות. אם יבוטל תהליך השמירה, כל השינויים יאבדו.",
	CARD_UPDATE_FAILURE: "Uploading of your notes about #### failed. Would you like to try again?",
	ABORT_UPLOAD: "ביטול עידכון והחזרת השינויים",
	DISMISS_DATA: "החזרת שינויים",
	RETRY_UPLOAD: "נסה לשמור שנית",
	CARD_WAS_DELETED: "Karte wurde gelöscht.",
	COULD_NOT_GET_TOPIC_REVISION: "Topic Revision konnte nicht geladen werden",
	
	RESET_FONT: "אתחל גופן",
	
	NOTIFICATION_MESSAGES: ["לחברך יש בעיה. הקישו כאן כדי לעזור"],
	NOTIFICATION_TITLES: ["בעיה חדשה"],
	NEEDS_SHARING_TO_GET_SOLVED_HTML: "<strong>תג זה אינו נראה למשתמשים אחרים</strong> בגלל שתיקיית ההערות איננה משותפת עם משתמשים אחרים. הקישו על מקש קהילה כדי לשתף את התיקייה.",
	PASTE_CURRENT_SELECTION: "הדבקת בחירה מדף ההערות.",
	NOTIFICATIONS: "חדשות מהקבוצה שלי",
	OPEN_INVITATIONS_HTML: "יש לך <span/>&nbsp;הזמנות קבוצה.",
	OPEN_REQUESTS_HTML: "ביקשת <span/>&nbsp;חברויות.",
	OPEN_OTHERS_REQUESTS_HTML: "יש <span/>&nbsp;בקשות חברות",
	QUESTION_REQUESTS_HTML: "יש <span/>&nbsp;בעיות שלא נפתרו",
	EMPTY_PROBLEM: "(אין שאלה פנויה)",
	FIND_FRIENDS_HEADER: "מציאת חברים",
	FIND_FRIENDS_MORE: "עוד...",
	SHARING_SUB_HEADER: "שיתוף",
	SHARING_MORE: "עוד...",
	SHARED_WITH: "תיקיית הערות משותפת בין כולם",
	UNSHARED: "תיקיית הערות לא שותפה עדיין",
	SHARED_WITH_YOU: "תיקיית הערות משותפת איתך",
	EDIT_SHARING_HEADER: " שתף ואשר חוקית את תיקיית ההערות הנוכחית",
	VIEW_SHARING_HEADER: "צפייה במידע השיתוף וברישיון",
	GROUP_FINDER_HEADER: "חיפוש בקבוצות",
	FIND_BUDDIES_HTML: "<p><strong>השתמשו בשדה החיפוש</strong> כדי למצוא חברים ללימודים, סתם חברים או קבוצות.</p>",
	NO_GROUP_RESULTS_HTML: "<p><strong>קבוצות לא נמצאו.</strong> נסו שאילתת חיפוש פחות ספציפית</p>",
	COULD_NOT_FIND_BUDDIES_QUESTION: "לא הצלחת למצוא את חבריך? צרו קבוצה חדשה והזמינו אותם!",
	NEWS: "הודעות",
	COULD_NOT_RETRIEVE_NOTIFICATION_MESSAGE: "לא יכול היה לאחזר הודעות.",
	NO_NOTIFICATIONS_HTML: "<p><strong>אין הודעות</strong>.</p>",
	COULD_NOT_HIDE_MESSAGE: "לא הצליח לסמן את ההודעה כהודעה שנקראה",
	INSERT_PAGE: "הוספת גליון פתקים",
	START_TOPIC: "תיקיית פתקים חדשה",
	BACK: "חזרה",
	FLIP_PAGE: "העברת דף",
	CREATE_NEW_TOPIC: "תיקיית הערות חדשה",
	CREATE_NEW_TOPIC_EXPLANATION: 'סגירת תיקיית ההערות הנוכחית ופתיחת חדשה.',
	CLEANUP_TOPIC: 'ניקוי תיקיית הערות',
	CLEANUP_TOPIC_EXPLANATION: 'הסרת דפי הערות ריקים מתיקיית ההערות',
	PROGRESS_HEADER: "תיקיית הערות נוכחית",
	NEW_MORE:"חדש...",
	NEW_TOPIC_EXPLANATION:"פתיחת תיקיית הערות חדשה",
	ADJUST_MORE:"עריכה...",
	ADJUST_EXPLANATION:"נהל את דפי ההערות הנוכחים, סדר אותם והכנס חדשים.",
	COULD_NOT_CHECK_REVISION: "לא הצליח לבדוק גרסאות חדשות לדף הערות זה.",
	COULD_NOT_SYNC_TRAINING: "נתוני אימון לא הצליחו להסתנכרן",
	TRASH_EMPTY: "לוח הכתיבה של התגים ריק",
	NO_CONTENT_FOR_HIGHLIGHT: "הסמן לא יכול לעבוד על דף ריק. יש לכתוב הערות קודם",
	NO_CONTENT_FOR_REINSERT: "תגים שהוסרו אינם יכולים להיכנס מחדש בדף הערות חדש.",
	MANAGE_TRASH: "ניהול לוח הכתיבה של התגים",
	INSERT_TRAINABLE_MARKERS: "כדי לשנן את דף הערות זה עליך להכניס הגדרות, שאלות ובעיות. אלו מאפשרים לקשר את השאלות שלך לתשובות הנובעות מחלקי הטקסט.",
	DO_MORE_FLASH_CARDS: " כדי לשנן בהצלחה את מה שכתוב בדף הערות זה, עליך קודם להכניס יותר תגים.",
	SEARCH_MY_TOPICS_HEADER: "חיפוש וניהול תיקיית הערות",
	FIND_MY_TOPIC_HTML: "<p><strong>השתמשו בשדה החיפוש</strong> כדי למצוא תיקיות הערות פנויות</p>",
	NO_RESULTS_OF_MY_TOPIC_SEARCH_HTML: "<p><strong>אף אחד מתקיות ההערות שלך אינו מתאים לשאילתא שלך</strong> נסו שאילתא פחות ספציפית</p>",
	SEARCH_ARTICLES_HEADER: "חיפוש וייבוא מאמרים",
	FIND_SEARCH_HTML: "<p><strong>השתמשו בשדה החיפוש</strong> כדי למצוא מאמרי וויקיפדיה ודפי הערות ששותפו ע\"י אחרים וזאת כדי לעבוד עליהם או לייצא אותם</p>",
	NO_RESULTS_HTML: "<p><strong>אין פריט שתאם לבקשתכם</strong> נסו להגדיר שאילתא פחות מפורטת.</p>",
	SEARCH_MORE: "נוסף...",
	DRAG_TO_LEFT_EXPLANATION: "ביחרו מלל וגררו אותו לתוך דף ההערות.",
	VIEW_RESULT_EXPLANATION: "תוצאות חיפוש מוצגות למטה.",
	COULD_NOT_LOAD_CARD: "לא הצליח לאחזר את דף ההערות הנבחר",
	DO_NOT_SHOW_AGAIN: "אל תראה שוב",
	WIKI_AJAX_URL: "http://en.wikipedia.org/w/api.php?action=opensearch&search=",
	SEARCH_WIKIPEDIA: 'חפש בוויקיפדיה',
	REMOVE_ALERT: "הסתרה",
	GROUP_ACCESS_READONLY: "לקריאה בלבד",
	GROUP_ACCESS_WRITE: "עריכה",
	GROUP_ACCESS_STRUCTURE: "התאם והרחב",
	GROUP_ACCESS_OWNER: "גישה מלאה",
	WIKI_URL: "http://en.wikipedia.org/w/index.php?title=",
	
	MAP_VIEW_EXPLANATION: "הראה תיקיית הערות נוכחית",
	COMMUNITY_EXPLANATION: "התחבר אל חבריך התלמידים ושתף אותם עם עבודתך",
	SEARCH_EXPLANATION: "חפשו בדף ההערות שלכם וייבאו מאמרים",
	MEMORIZE_EXPLANATION: "זכירת תגיות ע\"י שימוש בקופסת כרטיסיות",
	CLIPBOARD_EXPLANATION: "הכנסה חוזרת של תגים שהוסרו",
	INSERT_EXPLANATION: "הכניסו קישורים, תמונות ושאר תוכן מולטימדיה",
	
	PROBLEM_LIST_HEADING: "שאלות ותשובות",
	PROBLEM_LIST_HEADERS: ['שאלה', 'מצב', 'חבר', 'קבוצה'],
	
	ANSWERED: "אשר נענו",
	UNSOLVED: "שלא נענו",
	YOU: "אתם",
	BY_YOU: "אתם",
	
	INVITE_LIST_HEADERS: ['חבר', 'דואר'],
	
	SHARED_BY: "על ידי",
	GROUP_REQUESTED_FROM_TOPIC: "מנהלן צריך לאשר את בקשתכם. תוכלו לצפות בתיקיית ההערות ברגע שתצטרפו לקבוצה.",
	JOINED_GROUP: "קבוצה צורפה",
	CARD_LOCKED: "<strong> דף ההערות נערך ברגע זה</strong> ע\"י משתמש אחר והוא אינו יכול להשתנות.",
	STAY_READ_ONLY: "המשך קריאה בלבד",
	CHECK_OUT_TRY_AGAIN: "נסו שוב",
	
	CREATE_ADVANCED: "קחו הערות מתקדמות בקשר לדף ההערות הנוכחי",
	SWITCH_ADVANCED: "הצגת הערות מתקדמות",
	SWITCH_MAIN: "הצגת הערות חיוניות",
	CREATE_ILLUSTATIVE: "קחו הערות המחשה הקשורות לדף ההערות הנוכחי",
	SWITCH_ILLUSTATIVE: "הצגת הערות המחשה",
	
	TRAINER_OVERLAY_HEADER: "שינון דפי הערות",
	TRAINER_OVERLAY: "בחרו את <strong>טווח דפי ההערות</strong> שברצונכם לשנן",
	MEMORIZE_ALL: "תיקיית הערות שלמה",
	MEMORIZE_STUDIED: "דפים שנלמדו בפגישה זו",
	
	FIND_GROUP: "מציאת קבוצות",
	
	MINIMIZE: "הקטנה",
	MAXIMIZE: "הגדלה",
	
	COULD_NOT_LOAD_GROUPS: "לא מצליח לטעון קבוצות",
	
	REFER_FLOAT_CONTEXT: "(הקשר מוצג בלוח ההקשר)",
	
	LATEX_EDITOR: "עורך משוואות, LaTeX",
	BLOCK_MODE: "מצב חסום",
	RESET_SIZE: "אתחל גודל",
	HELP: "עזרה...",
	LATEX_HELP_LINK: "http://www.mediabird.net/en/about/latex",
	
	UNKNOWN: "לא ידוע",
	PROBLEM_SOLVED: 'בעיה נפתרה!',
	
	AUTHOR: 'מחבר',
	
	INVITATION: "הזמנה",
	REQUEST_BY: "התבקשה על ידי",
	
	INSERT_TABLE: "טבלה",
	
	EXTERNAL_REFERENCE: "קישור חיצוני",
	CLICK_TO_FOLLOW: 'הקליקו לפתיחת הקישור',
	REFERENCES: "קישורים",
	RELATIONS_LIST_HEADERS: ['מיקום', 'פעולה'],
	EDIT_REFERENCE: 'עריכת קישור',
	
	QUICK_REFERENCE: "הכנסת קישור מהיר",
	LINK_CURRENT: "לדף נוכחי",
	LINK_CURRENT_EXPLANATION: "מוסיף איזכור לדף שמוצג מחוץ לפנקס",
	LINK_CURRENT_NOTE: "להערות בלוח",
	LINK_CURRENT_NOTE_EXPLANATION: "מוסיף איזכור לדף ההערות המוצג מימין",
	LINK_CURRENT_WIKI: "למאמר וויקיפדיה",
	LINK_CURRENT_WIKI_EXPLANATION: "מוסיף איזכור לכתבת הוויקיפדיה המוצגת מימין",
	
	REF_EXISTS: "כבר נוסף איזכור עם אותו מיקום",
	ERROR_REF_EMPTY: "מיקום או כותרת חסרים",
	
	LOGOUT: 'התנתק',
	
	OPEN_SHEET: "הצגת גיליון ",
	
	ALERT_HEADER: "מידע",
	
	GIVE_US_FEEDBACK: "תנו לנו קצת משוב",
	SEND_FEEDBACK: "שליחת משוב",
	SEND: "שליחה",
	MESSAGE_EMPTY: "ההודעה שלך ריקה",
	THANKS_FEEDBACK: "<h3>תודה על המשוב.</h3><p>אנו נתמודד איתו בהקדם האפשרי</p>",
	FEEDBACK_ERROR: "לא הצליח לשלוח את המשוב שלך",
	
	FOLLOW_LINK: "עקוב אחר קישור",
	EDIT_LINK: "ערוך קישור",
	
	INSERT_COLUMN : "הכנסת טור",
	INSERT_ROW : "הכנסת שורה",
	DELETE_COLUMN : "מחיקת טור",
	DELETE_ROW : "מחיקת שורה",
	TOPIC_COULD_NOT_BE_UPDATED: "הסידור של תיקיית ההערות לא הצליח להתעדכן. אינכם יכולים למחוק דף הערות שנמצא בעריכה ע\"י מישהו אחר.",
	
	DELETE_TOPICS: "מחיקת תיקיות הערות שנבדקו",
	DELETE_TOPICS_CONFIRM: "תיקיות ההערות הבאות ימחקו:\n####\n\nהאם להמשיך?",
	COULD_NOT_DELETE_TOPICSS: "לא הצליח למחוק את תיקיות ההערות שנבחרו",
	
	MANAGE_TOPICS: "ניהול תיקיות הערות",
	SWITCH_TO_FULL: "צפו בדף ההערות בעזרת מאפיינים מתקדמים",
	
	TOPICS_SHARED_WITH_GROUP: "תיקיות הערות שמשותפות עם קבוצה",
	GROUP_TOPIC_LIST_HEADERS: ["תיקיית הערות", "יוצר", "גישה"],
	MAX_NO_OF_CARDS_IN_TOPIC: "תיקיית הערות מלאה. היא מכילה את מקסימום דפי ההערות שהיא יכולה. צרו תיקייה חדשה או סדרו את ההערות בצורה שונה.",
	NO_GROUP_CHANGES: "אין שינויים מאז השמירה האחרונה."
}
