<?php
$string['browser_cap'] = 'Recursos do Navegador';
$string['browser_support'] = 'O seu navegador <em>aparentemente</em> possui suporte aos seguintes recursos:';
$string['browser_noscript'] = 'você não tem o Javascript habilitado, que é necessário para o funcionamento deste plugin';
$string['browser_cap_config_intro'] = 'Selecione os plugins que voc&ecirc; gostaria que fossem verificados pelo bloco. Os alunos do seu curso poder&atilde;o visualizar uma marca de verifica&ccedil;&atilde;o para cada um destes itens indicando se o seu navegador possui suporte ao plugin ou n&atilde;o. Se voc&ecirc; sabe que n&atilde;o est&aacute; utilizando qualquer um destes plugins, voc&ecirc; pode remover a verifica&ccedil;&atilde;o deste plugin. <strong>Observa&ccedil;&atilde;o:</strong> este bloco somente <em>indicar&aacute;</em> a presen&ccedil;a do suporte ao plugin. N&atilde;o mostrar&aacute; qual a vers&atilde;o suportada pelo navegador.';
$string['adobe_desc'] = 'O Adobe Portable Document Format (PDF) &eacute; um formato de arquivo comumente utilizado pelos criadores de conte&uacute;dos web. Este formato &eacute; facilmente visualiz&aacute;vel em m&uacute;ltiplos Sistemas Operacionais com o aux&iacute;lio de um plugin PDF, como o Adobe Acrobat Reader.';
$string['cookies_desc'] = 'Os cookies s&atilde;o um requisito importante e necess&aacute;rio para acessar ao ambiente Moodle, portanto, n&atilde;o &eacute; realmente necess&aacute;rio verificar o seu suporte.';
$string['flash_desc'] = 'Assim como o Java, o Flash permite aos autores oferecer um conte&uacute;do din&acirc;mico e interativo na web. Voc&ecirc; precisar&aacute; do Flash Player para aproveitar estas funcionalidades.';
$string['java_desc'] = 'O Java Runtime Environment (JRE) permite aos usu&aacute;rios visualizar e rodar aplica&ccedil;&atilde;es web criadas utilizando a linguagem de programa&ccedil;&atilde;o Java.';
$string['javascript_desc'] = 'Outra importante tecnologia utilizada no Moodle. Assim como acontece com os cookies, no entanto, n&atilde;o &eacute; necess&aacute;rio verificar, portanto, de fato, esta bloco n&atilde;o vai funcionar sem o suporte a JavaScript.';
$string['quicktime_desc'] = 'Se voc&ecirc; estiver utilizando arquivos em formato do QuickTime (.qt) em seu curso, ou possui links apontando para este tipo de recurso, os alunos dever&atilde;o ter suporte a este tipo de plugin.';
$string['real_desc'] = 'Se voc&ecirc; estiver utilizando arquivos em formato Real Media (.rm) em seu curso, ou possui links apontando para este tipo de recurso, os alunos dever&atilde;o ter suporte a este tipo de plugin.';
$string['windows_media_desc'] = 'Se voc&ecirc; estiver utilizando arquivos em formato Windows Media (.vm ou .wav) em seu curso, ou possui links apontando para este tipo de recurso, os alunos dever&atilde;o ter suporte a este tipo de plugin.';
$string['tech_notes'] = 'Notas T&eacute;cnicas';
$string['tech_notes_desc'] = '<p>Esta solu&ccedil;&atilde;o, como &eacute; implementada utilizando os m&eacute;todos navigator.*, suportados pelos navegadores Mozilla, Firefox e antigas vers&otilde;es do IE para verificar o a disponibilidade do suporte destes plugins. E utiliza objetos ActiveX nas &uacute;ltimas vers&otilde;es do IE, com alguns scripts escritos em linguagem VBScript. Embora n&atilde;o seja t&atilde;o confi&aacute;vel, estas fun&ccedil;&otilde;es fornecem uma indica&ccedil;&atilde;o rezo&aacute;vel sem sobrecarga para a cria&ccedil;&atilde;o de cada tipo de objeto.</p><p>A maioria dos plugins de detec&ccedil;&atilde;o utiliza solu&ccedil;&otilde;es tentando criar uma inst&acirc;ncia do objeto em quest&atilde;o, ao incluir a tag &lt;object&gt; na sa&iacute;da e, em seguida verificar se existe, ou se o objeto &eacute; capaz de ser consultado atrav&eacute;s dos seus m&eacute;todos/propriedades. Se o detector n&atilde;o consegue se comunicar com o objeto, este assume que o plugin n&atilde;o est&aacute; dispon&iacute;vel, ou est&aacute; desativado.</p><p>Este m&eacute;todo &eacute; eficaz, por&eacute;m coloca uma maior carga de rede para o navegador e, potencialmente, tamb&eacute;m no servidor, que n&aacute;o pode ser apropriado em uma p&aacute;gina que &eacute; freq&uuml;entemente visitada.</p>';
?>
